ka-extension/ka-extension-ts

- src/report.ts
This works perfectly well, except it doesn't show the parent of the whole thread. I'm not sure if there is an endpoint that gets the thread parent _and_ replies, but for the moment it just downloads a JSON file of the replies to a specific thread.
> Add download replies button

- .travis.yml
Language is Node.js; node version is `node`, aka "latest stable Node.js release"; I think default install cmd is `npm install`, but I want to be explicit; run our build script.
> Setting up Travis config

- src/extension-impl.ts
- src/project.ts
- src/types/data.ts
Replaces KA's vote button with a better one. Fixes #83.
The two goals of this were to update the vote button to say "Voted Up" after clicking the vote button, (before reloading the page), and to allow undoing votes. The easiest way to do this was to completely replace KA's vote button with our own with custom Javascript.
We lose KA's nice error popup (instead using `alert`), and there is a flash where the old vote button is visible, but I think it's worth this trade off for the above features.
Some concerns before merging:
- I don't currently put any special extension item class on the new vote button.
- I don't know Typescript. I got rid of the compile-time type errors, but if there's something I could have done better with my variable types, we should fix that.
- I actually haven't …
> Replace vote button

- src/extension-impl.ts
- src/project.ts
- styles/general.css
Adds a button to the program button row that, when clicked, copies a shorted link to the program to the user's clipboard.
Also creates a BUTTON_CLASSES constant with the active and non-active state class names KA uses for buttons in this row.
I just threw the `BUTTON_CLASSES` constant into `program.ts`, but it might make more sense to put it somewhere else, like `data.ts`. (Also maybe `buttonClasses.ACTIVE` instead of `BUTTON_CLASSES.active`.)
A good portion of this code, lines 196 to 210, handle copying to the clipboard for browsers older than Chrome 66 and Firefox 63. If we're not interested in supporting those browsers, it's worth removing those lines.
> Add program link button

- src/extension-impl.ts
- src/extension.ts
- src/project.ts
On project pages, add an event listener to make a call to create a hover qtip when the author's nickname is hovered over. This broke after the nickname-bluing KA update.
I was going to try to add this to display names on browse projects pages as well (#21), but I couldn't get the cards to show up in the right places. I might look into it again in the future. I wanted this to be available to roll out with the buttons becoming blue.
> Add hover cards to program author nicknames

- styles/general.css
I'm not OCD, but it bothers me when things aren't centered.
- KA never centered program titles, but just kind of left aligned them a third of the way across the page.
- T&T under programs were being pushed far to the left by KA and the extension's CSS. This centers the discussion container under programs and squeezes the Community Guidelines into a slightly smaller area to the right.
Before:
After:
> Center program titles and discussion

- styles/general.css
Adds some CSS to hide KA's feedback survey. 
This survey annoys me, mostly because the questions it asks aren't relevant to frequent KA users.
> Hide survey

- src/buttons.ts
Try to fix the issues ABoss and Thomas were having with voting.
Specify `credentials: "same-origin"`. This is the default option in the recent version of the spec, but in older versions it's "omit", which leads to cookies not getting sent and then the vote fails.
Change the VOTE_URL to be relative. This makes sure that the request is actually a "same-origin" request and credentials get sent.
Move error handling outside of the .then for JSON parsing, and add an alert to the `.catch` of JSON parsing. This way if KA returns "Unauthorized" (and JSON parsing fails), the user still gets feedback.
(These commits can probably also be squashed.)
> Vote fixes

- src/buttons.ts
- src/extension-impl.ts
- styles/general.css
- Also fixes the issue Chrome users were having where the extension CSS was being overwritten by KA's CSS, by making the rules more specific. Adding the `#page-content` parent requirement makes our rules take precedent over KA's more general rules. (I know, it's not elegant.)
- Sets a background on the disabled save button so it's not green
- Moves around some style rules.
- Make all buttons solid blue.
- Make all disabled buttons outlined (grayer) blue.
- Make the sort buttons on the browse projects page blue.
- Adds some comments explaining what rules target what.
- Remove the empty text nodes in between some of the program buttons, as they were making the spaces inconsistent.
- Force the Spin-off button to have the same amount of right margin as the Save button, overwriting the inline …
> Improve button styling

- src/buttons.ts
- src/project.ts
- styles/general.css
The toolbar under projects on KA updated. This introduces fixes for issues with the "Toggle Editor Settings" and "Toggle Editor" buttons that arose as a result of that.
**Toggle Editor Settings**
- It is now appended to the left half of the area under the editor, so the pop-up has room to expand to the right.
- It now uses the new styling, matching the Spin Off button.
- Adds CSS for handling hovering (which KA uses jQuery for) and text styling (KA uses another wrap element).
- Removes a spacer that was around this button.
- Removes the CSS for the toggle dark theme button that never got removed.
- Removes CSS that messed with the .pull-right class as part of evenly spacing buttons in this toolbar (#133). This class isn't used here anymore.
- Restyles Error Buddy to not be absolutely …
> Fixes for KA's new toolbar

- src/project.ts
Fixes #134 
I think this wasn't done earlier because it didn't work will with the variable width HTML output, but it works fine now, after the change to not use `kae-hide-NUMBER` CSS [here](https://github.com/ka-extension/ka-extension-ts/commit/7c2ce2776271e8b662fefe58728ead252b74eb5e#diff-643734ad32af0ee6927f50dac98486f5L51)
> Make Toggle Editor work on webpages

- src/buttons.ts
- src/extension-impl.ts
- src/report.ts
- styles/general.css
Fixes #146. 
#133:
> Remove the empty text nodes in between some of the program buttons, as they were making the spaces inconsistent.
This method was causing issues with the Share button, for reasons I don't fully understand. This PR fixes those issues by changing button respacing to be done primarily in CSS. We add text nodes to buttons that didn't have one instead of removing text nodes.
This also changes how the CSS for the report buttons is handled.
This also switches to use `body` instead of `#page-container` in CSS.
This is needed to make sure our CSS takes precedence over KA's, and both `#page-container` and `body` have that effect.
We should be consistent, however. Ethan had used `body` prior to me using `#page-container,` and it's shorter, so this switches everything to `body`.
> Fix share button

- src/extension.ts
Add a check to the About tab button to check if it's selected, and only re-add the elements to the page if it's not selected.
Fixes #148
> Fix About Tab Duping

- src/editor-settings.ts
Remove themes that didn't work, fixing #162. Also closes #163.
Also re-orders the themes so the light themes are at the top and the dark themes are at the bottom.
> Fix ace themes

- src/background.ts
- src/buttons.ts
- src/content.ts
- src/editor-settings.ts
- src/extension-impl.ts
- src/extension.ts
- src/flag.ts
- src/index.ts
- src/notif.ts
- src/profile.ts
- src/project.ts
- src/types/data.ts
- src/types/message-types.ts
- src/util/promise-util.ts
- tslint.json
This commit adds the tslint rule `no-any` and fixes all subsequent lint errors.
There are a few lines on which tslint ignore is used, mostly in inevitable situations
like defining types for the `window.ace` object.
> Remove `any` type declarations

- src/util/data-util.ts
Ref #217
Kinda hacky, but it works.
This bug _needs_ a fix as soon as possible, so maybe this will do the job for now.
This PR brings back the extra statistics too:
> Modify getKAID function to use localStorage to query KAID

- styles/general.css
> Enable scrolling for overflow in badge descriptions

- styles/general.css
Closes #32 
Surely there is a better way to get the identity of that container?
I couldn't work it out though.
> Remove max-width for spinoffs container

- styles/general.css
Add margin between project feedback tabs to be how it was originally.
> Add margin for project feedback tabs

- styles/general.css
(Maybe merge into 1 PR with #207?)
Currently styled as black whereas previously it was colored as a link.
In my opinion, it felt that it was more obvious that one could click the 'button' to refresh the project feedback list.
CURRENT <<< >>> UPDATED
> Add link styling to refresh button on project feedback page

- src/popup.ts
- src/types/data.ts
> Add support for avatar rewards ( + fix date overlapping with title)

- src/extension-impl.ts
- src/extension.ts
- src/profile.ts
Closes: #33
Related issues: #19
This PR implements a method in which it's possible to modify badge descriptions on the user visiting the badges page in either the profile or the badge showcase.
`profile/${uok}/badges`:
`badges/tesla`:
> Implement customization code for badges (+ tesla badge description)

- package-lock.json
- src/extension-impl.ts
- src/project.ts
Updated to
- use getKAID function defined in data-util.ts
- use querySelectorPromise
- use userAuthoredContentType from onProgramPage argument
- avoid saving the code to localStorage if we aren't currently on a new scratchpad page
I don't think we need to worry about naming collisions with KA because the extension is storing the same data. Using the same key prevents us from storing duplicate data and wasting memory.
> Fixed saving new scratchpads to localStorage
